import { flexDirection } from "../theme/flexDirection";
export enum CssPropertyMappings {
  // Colors
  borderBottomColor = "colors",
  backgroundColor = "colors",
  borderColor = "colors",
  background = "colors",
  altColor = "colors",
  fontColor = "colors",
  color = "colors",

  // Sizes
  borderRadius = "sizes",
  maxHeight = "sizes",
  minHeight = "sizes",
  minWidth = "sizes",
  maxWidth = "sizes",
  padding = "sizes",
  margin = "sizes",
  mx = "sizes",
  my = "sizes",
  px = "sizes",
  py = "sizes",
  pt = "sizes",
  pr = "sizes",
  pb = "sizes",
  pl = "sizes",
  mt = "sizes",
  mr = "sizes",
  mb = "sizes",
  ml = "sizes",
  p = "sizes",
  m = "sizes",
  left = "sizes",
  right = "sizes",
  top = "sizes",
  bottom = "sizes",
  gap = "sizes",

  // Flexbox
  justifyContent = "justifyContent",
  flexDirection = "flexDirection",
  alignItems = "alignItems",
  alignContent = "alignContent",
  alignSelf = "alignSelf",
  flexWrap = "flexWrap",

  // Display
  display = "display",
  zIndex = "zIndex",

  // Miscellaneous
  cursor = "cursor",
  objectFit = "objectFit",
  objectPosition = "objectPosition",
  fontWeight = "fontWeight",
  height = "widthHeight",
  width = "widthHeight",
  boxSizing = "boxSizing",
  fontSize = "fontSize",
  borderBottom = "border",
  borderRight = "border",
  borderLeft = "border",
  borderTop = "border",
  border = "border",
  animation = "animation",
  keyframes = "keyframes",
  after = "after",
  before = "before",
  inset = "inset",
  transform = "transform",
  content = "content",
  clipPath = "clipPath",
  lineHeight = "lineHeight",
  fontFamily = "fontFamily",
  outline = "outline",
  textAlign = "textAlign",
  hover = "hover",

  // Positioning
  position = "position",
  flexShrink = "flexShrink",
  fontStyle = "fontStyle",
}
